version: "3.9"
services:
   db:
      container_name: db
      image: "postgres:14"
      ports: 
      - "5432:5432"
      environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_PASSWORD=${PASSWORD}
      networks:
         node_net:
            ipv4_address: ${HOST}
   app:
      container_name: uporabnik
      image: "tp7220/uporabniki"
      ports:
      - "5003:5003"
      environment:
      - DATABASE_IP=172.27.1.2
      - PGUSER=${USER}
      - PGDATABASE=${DATABASE}
      - PGPASSWORD=${PASSWORD}
      networks:
         node_net:
            ipv4_address: 172.27.1.3

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/16
