version: "3.9"
services:
   db:
      image: "postgres:13"
      ports: 
      - "5432:5432"
      environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      networks:
         node_net:
            ipv4_address: ${PGHOST}
   app:
      image: "tp7220/uporabniki:latest"
      ports:
      - "5000:5000"
      networks:
         node_net:
            ipv4_address: 172.27.1.3

   prometheus:
      image: prom/prometheus:v2.26.0
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
      - "9090:9090"
      networks:
         node_net:
            ipv4_address: 172.27.1.2

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/16
