apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-uporabniki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-uporabniki
  template:
    metadata:
      labels:
        app: postgres-uporabniki
    spec:
      containers:
        - image: postgres:13
          name: postgres-uporabniki
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "uporabniki"
          ports:
          - containerPort: 5432
            protocol: TCP
--- 

apiVersion: v1
kind: Service
metadata:
  name: postgres-uporabniki
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-uporabniki