name: App multistage package and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup pip environment and deps
      run: |
         python -m pip install --upgrade pip
         pip install -U pipenv
         pipenv install pytest
         pipenv install black

    - name: Run app
      run: docker-compose up -d

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Code static check
      run: pipenv run black api.py

    - name: Run python unittests
      run: pipenv run pytest

    - name: Kill app
      run: docker-compose down

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/uporabniki:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}  
